version: "3"

services:
  db:
    image: mysql:8.0
    volumes:
      - /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=vitor
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=db01
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    links:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: vitor
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root      